### ISSUE TITLE
The training stops after 10 epochs

### ISSUE THREAD

**Issue by Hayashi-Yudai** [Hayashi-Yudai/ML_models#38]
When training ACoL, the training process always stop at 10th epoch with following error message.

```
2019-07-13 20:36:33.624900: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at strided_slice_op.cc:106 : Invalid argument: slice index 4 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "train.py", line 68, in <module>
    train(parser)
  File "train.py", line 61, in train
    callbacks=[csvLogger, callback]
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2177, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 176, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1932, in train_on_batch
    self, x, y, sample_weights=sample_weights)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 556, in train_on_batch
    model, inputs, targets, sample_weights=sample_weights, training=True)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 511, in _process_single_batch
    training=training)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_eager.py", line 90, in _model_loss
    outs, masks = model._call_and_compute_mask(inputs, **kwargs)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 856, in _call_and_compute_mask
    mask=masks)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1052, in _run_internal_graph
    output_tensors = layer.call(computed_tensors, **kwargs)
  File "/home/yudai/Documents/Python/MachineLearning/ML_models/ACoL/model.py", line 50, in call
    a = tf.reshape(interm[bt, :, :, max_idx[bt]], [7, 7, 1])
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 525, in _slice_helper
    name=name)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 691, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/yudai/.conda/envs/tf-gpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8556, in strided_slice
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 4 of dimension 0 out of bounds. [Op:StridedSlice] name: adversarial/strided_slice/
```

**Comment by Hayashi-Yudai** [comment]
batch size is hard coded in the model. This cause the shape error at the last batch except for the data size is the multiple of the batch size

```
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 224, 224, 3)  0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 224, 224, 64) 1792        input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv2 (Conv2D)           (None, 224, 224, 64) 36928       block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_pool (MaxPooling2D)      (None, 112, 112, 64) 0           block1_conv2[0][0]               
__________________________________________________________________________________________________
block2_conv1 (Conv2D)           (None, 112, 112, 128 73856       block1_pool[0][0]                
__________________________________________________________________________________________________
block2_conv2 (Conv2D)           (None, 112, 112, 128 147584      block2_conv1[0][0]               
__________________________________________________________________________________________________
block2_pool (MaxPooling2D)      (None, 56, 56, 128)  0           block2_conv2[0][0]               
__________________________________________________________________________________________________
block3_conv1 (Conv2D)           (None, 56, 56, 256)  295168      block2_pool[0][0]                
__________________________________________________________________________________________________
block3_conv2 (Conv2D)           (None, 56, 56, 256)  590080      block3_conv1[0][0]               
__________________________________________________________________________________________________
block3_conv3 (Conv2D)           (None, 56, 56, 256)  590080      block3_conv2[0][0]               
__________________________________________________________________________________________________
block3_pool (MaxPooling2D)      (None, 28, 28, 256)  0           block3_conv3[0][0]               
__________________________________________________________________________________________________
block4_conv1 (Conv2D)           (None, 28, 28, 512)  1180160     block3_pool[0][0]                
__________________________________________________________________________________________________
block4_conv2 (Conv2D)           (None, 28, 28, 512)  2359808     block4_conv1[0][0]               
__________________________________________________________________________________________________
block4_conv3 (Conv2D)           (None, 28, 28, 512)  2359808     block4_conv2[0][0]               
__________________________________________________________________________________________________
block4_pool (MaxPooling2D)      (None, 14, 14, 512)  0           block4_conv3[0][0]               
__________________________________________________________________________________________________
block5_conv1 (Conv2D)           (None, 14, 14, 512)  2359808     block4_pool[0][0]                
__________________________________________________________________________________________________
block5_conv2 (Conv2D)           (None, 14, 14, 512)  2359808     block5_conv1[0][0]               
__________________________________________________________________________________________________
block5_conv3 (Conv2D)           (None, 14, 14, 512)  2359808     block5_conv2[0][0]               
__________________________________________________________________________________________________
block5_pool (MaxPooling2D)      (None, 7, 7, 512)    0           block5_conv3[0][0]               
__________________________________________________________________________________________________
conv2d (Conv2D)                 (None, 7, 7, 1024)   4719616     block5_pool[0][0]                
__________________________________________________________________________________________________
batch_normalization (BatchNorma (None, 7, 7, 1024)   4096        conv2d[0][0]                     
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 7, 7, 1024)   9438208     batch_normalization[0][0]        
__________________________________________________________________________________________________
batch_normalization_1 (BatchNor (None, 7, 7, 1024)   4096        conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 7, 7, 10)     10250       batch_normalization_1[0][0]      
__________________________________________________________________________________________________
batch_normalization_2 (BatchNor (None, 7, 7, 10)     40          conv2d_2[0][0]                   
__________________________________________________________________________________________________
global_average_pooling2d (Globa (None, 10)           0           batch_normalization_2[0][0]      
__________________________________________________________________________________________________
softmax (Softmax)               (None, 10)           0           global_average_pooling2d[0][0]   
__________________________________________________________________________________________________
adversarial (Adversarial)       (20, 7, 7, 512)      0           block5_pool[0][0]                
                                                                 batch_normalization_2[0][0]      
                                                                 softmax[0][0]                    
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (20, 7, 7, 1024)     4719616     adversarial[0][0]                
__________________________________________________________________________________________________
batch_normalization_3 (BatchNor (20, 7, 7, 1024)     4096        conv2d_3[0][0]                   
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (20, 7, 7, 1024)     9438208     batch_normalization_3[0][0]      
__________________________________________________________________________________________________
batch_normalization_4 (BatchNor (20, 7, 7, 1024)     4096        conv2d_4[0][0]                   
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (20, 7, 7, 10)       10250       batch_normalization_4[0][0]      
__________________________________________________________________________________________________
batch_normalization_5 (BatchNor (20, 7, 7, 10)       40          conv2d_5[0][0]                   
__________________________________________________________________________________________________
segmentation (segmentation)     (20, 7, 7)           0           batch_normalization_2[0][0]      
                                                                 batch_normalization_5[0][0]      
                                                                 softmax[0][0]                    
==================================================================================================
Total params: 43,067,300
Trainable params: 28,344,380
Non-trainable params: 14,722,920
__________________________________________________________________________________________________
```

**Comment by Hayashi-Yudai** [comment]
Fixing in [this branch](https://github.com/Hayashi-Yudai/ML_models/tree/hayashi/fix_acol_bug).
